readme: updates
Unvanquished/Unvanquished pull request #2120
Opened 2022-08-29 20:17 UTC by illwieckz

More readme updates.

I also squashed the commit for an unsolved thread in https://github.com/Unvanquished/Unvanquished/pull/2087

2022-08-30 11:39 UTC, necessarily-equal approved these changes

2022-08-30 11:39 UTC, necessarily-equal commented on README.md
> +Otherwise you can use the package downloader script. This script can use `aria2c`, `curl` or `wget`, `aria2c` is recommended.
```suggestion
Otherwise you can use the package downloader script. This script can use `aria2c`, `curl` or `wget`. `aria2c` is recommended.
```

2022-08-30 11:39 UTC, necessarily-equal commented on README.md
> +For debugging purpose, you can run your mod as dll:
```suggestion
For debugging purpose, you can run your mod as a shared library:
```

2022-08-30 14:49 UTC, necessarily-equal requested changes

2022-08-30 14:49 UTC, necessarily-equal commented on README.md
> +./daemonded set fs_extrapaks mod-custom +map plat23
```suggestion
./daemonded -set fs_extrapaks mod-custom +map plat23
```
(or maybe `+set` works too)

2022-08-31 23:24 UTC, illwieckz commented on README.md
> +Otherwise you can use the package downloader script. This script can use `aria2c`, `curl` or `wget`, `aria2c` is recommended.
Done

2022-08-31 23:24 UTC, illwieckz commented on README.md
> +./daemonded set fs_extrapaks mod-custom +map plat23
Done

2022-08-31 23:24 UTC, illwieckz commented on README.md
> +For debugging purpose, you can run your mod as dll:
Done

2022-08-31 23:31 UTC, necessarily-equal commented
GitHub is missing this feature GitLab has where you can diff with the previous version of the PR you reviewed, and I guess you didn't change that much so I don't think I'll be reviewing it again. I think you can merge it when it's ready™

2022-08-31 23:40 UTC, illwieckz commented
Yeah, I addressed the issues you pointed out and reworded some wordy words in most concise manner.

Something I'm looking for a comment: I tried to add some ℹ️ and 💡️ emojis to mark some “ℹ️  Notable info” and some “💡️ Clever trick”. What do you think about it?

2022-09-01 19:19 UTC, DolceTriade commented
lgtm

2022-09-03 21:45 UTC, merged