Kill ghost buildings to ensure decrementing the spawn counters
Unvanquished/Unvanquished pull request #3074
Opened 2024-07-26 08:00 UTC by sweet235

You can encounter ghost eggs frequently in the wild. They are very annoying. The egg does not exist, but the spawn counter will never go down to zero. They might be in a map's builtin layout or in a layout someone saved two years ago. One example is map moonbase.

Why are there ghost eggs at all? I do not know. Probably because of changes to the trace code.

Policy dicatates to modify the spawn counters only in the CBSE components. I am not a CBSE expert, so I cannot promise this is correct. Are there any CBSE experts?

2024-07-26 09:14 UTC, cu-kai requested changes

2024-07-26 09:35 UTC, cu-kai approved these changes
LGTM

2024-07-26 13:33 UTC, slipher commented
> Why are there ghost eggs at all?

Could be because the buildable has a different bbox size.

LGTM

2024-07-27 15:08 UTC, sweet235 commented
Someone said bisecting leads to 117e11bcc71417ae14150d635c98082defdfa12a.

2024-07-27 17:43 UTC, sweet235 commented
Thinking about this, fixing this might actually require a CBSE expert.

2024-08-05 03:12 UTC, merged